export const FETCH_ALL_CUSTOMERS_PENDING = "FETCH_ALL_CUSTOMERS_PENDING";
export const FETCH_ALL_CUSTOMERS_SUCCESS = "FETCH_ALL_CUSTOMERS_SUCCESS";
export const FETCH_ALL_CUSTOMERS_FAILED = "FETCH_ALL_CUSTOMERS_FAILED";

export const ADD_CUSTOMER_PENDING = "ADD_CUSTOMER_PENDING";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAILED = "ADD_CUSTOMER_FAILED";

export const REMOVE_CUSTOMER_PENDING = "REMOVE_CUSTOMER_PENDING";
export const REMOVE_CUSTOMER_SUCCESS = "REMOVE_CUSTOMER_SUCCESS";
export const REMOVE_CUSTOMER_FAILED = "REMOVE_CUSTOMER_FAILED";

export const EDIT_CUSTOMER_PENDING = "EDIT_CUSTOMER_PENDING";
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER_FAILED = "EDIT_CUSTOMER_FAILED";

export const SELECT_CUSTOMER_PENDING = "SELECT_CUSTOMER_PENDING";
export const SELECT_CUSTOMER_SUCCESS = "SELECT_CUSTOMER_SUCCESS";
export const SELECT_CUSTOMER_FAILED = "SELECT_CUSTOMER_FAILED";

export const BASE_URL = `http://localhost:8000/customers`;
