export const FETCH_ALL_PINS_PENDING = "FETCH_ALL_PINS_PENDING";
export const FETCH_ALL_PINS_SUCCESS = "FETCH_ALL_PINS_SUCCESS";
export const FETCH_ALL_PINS_FAILED = "FETCH_ALL_PINS_FAILED";

export const ADD_PIN_PENDING = "ADD_PIN_PENDING";
export const ADD_PIN_SUCCESS = "ADD_PIN_SUCCESS";
export const ADD_PIN_FAILED = "ADD_PIN_FAILED";

export const REMOVE_PIN_PENDING = "REMOVE_PIN_PENDING";
export const REMOVE_PIN_SUCCESS = "REMOVE_PIN_SUCCESS";
export const REMOVE_PIN_FAILED = "REMOVE_PIN_FAILED";

export const EDIT_PIN_PENDING = "EDIT_PIN_PENDING";
export const EDIT_PIN_SUCCESS = "EDIT_PIN_SUCCESS";
export const EDIT_PIN_FAILED = "EDIT_PIN_FAILED";

export const SELECT_PIN_PENDING = "SELECT_PIN_PENDING";
export const SELECT_PIN_SUCCESS = "SELECT_PIN_SUCCESS";
export const SELECT_PIN_FAILED = "SELECT_PIN_FAILED";

export const BASE_URL = `http://localhost:8000/pins`;
