export const FETCH_ALL_POSTS_PENDING = "FETCH_ALL_POSTS_PENDING";
export const FETCH_ALL_POSTS_SUCCESS = "FETCH_ALL_POSTS_SUCCESS";
export const FETCH_ALL_POSTS_FAILED = "FETCH_ALL_POSTS_FAILED";

export const FETCH_ONE_POST_PENDING = "FETCH_ONE_POST_PENDING";
export const FETCH_ONE_POST_SUCCESS = "FETCH_ONE_POST_SUCCESS";
export const FETCH_ONE_POST_FAILED = "FETCH_ONE_POST_FAILED";

export const ADD_POST_PENDING = "ADD_POST_PENDING";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILED = "ADD_POST_FAILED";

export const REMOVE_POST_PENDING = "REMOVE_POST_PENDING";
export const REMOVE_POST_SUCCESS = "REMOVE_POST_SUCCESS";
export const REMOVE_POST_FAILED = "REMOVE_POST_FAILED";

export const EDIT_POST_PENDING = "EDIT_POST_PENDING";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAILED = "EDIT_POST_FAILED";

export const SELECT_POST_PENDING = "SELECT_POST_PENDING";
export const SELECT_POST_SUCCESS = "SELECT_POST_SUCCESS";
export const SELECT_POST_FAILED = "SELECT_POST_FAILED";

export const BASE_URL = `http://localhost:8000/blog_posts`;
